services:
  api:
    image: osrs-bot-api
    build:
      context: ./bot-api
      dockerfile: Dockerfile
    ports:
      - 3000:8080
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:3306
    networks:
      - default
